### PR TITLE
feat: mdx improvements

### PR DESCRIPTION
**Pull request by yqrashawn**
GEN-1074

1. move copy button to code highlighter
2. generate id for h1-h6

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1208270495871404

### CODE REVIEW

**Comment by yqrashawn** [comment]
Anyone know why `MDXRmote` is used in this project?
I checked several usages, and it seems most data are fetched from within this project itself. Why not render the markdown at server side?

**Comment by yqrashawn** [comment]
> Is this a task that you can help with?

Yes, although I got tasks on other projects, it depends on @zzq0826

**Comment by zzq0826** [comment]
> > Is this a task that you can help with?
> 
> Yes, although I got tasks on other projects, it depends on @zzq0826

I've noted this requirement, but we currently have other tasks in progress. Once we have the bandwidth, we can work on this.

**Comment by PrintRH** [comment]
Awesome! Thank you @yqrashawn & @zzq0826 , that would be a great help!

For now, what would be our preference for this PR? Do we want to merge this PR or keep it open to have till we have ssr task also integrated then merge?

We're fine with both options.

**Comment by zzq0826** [comment]
If the current PR meets your requirements, I suggest we deploy it first and optimize it later.

**Comment by PrintRH** [comment]
Cool! This LGTM! Changes are aligned with ticket asks.

As a sanity check, can I also get your review on this PR @zzq0826 ?

**Comment by PrintRH** [comment]
@yqrashawn - I just noticed one thing in this PR. Seems like the `MDXCodeHighlighter` component is wrapped inside another container. Was this created to distinguish a copyable code snippet vs those that is not copyable? Let me know if you'd like me to point it out via Vercel.

**Comment by yqrashawn** [comment]
> @yqrashawn - I just noticed one thing in this PR. Seems like the `MDXCodeHighlighter` component is wrapped inside another container. Was this created to distinguish a copyable code snippet vs those that is not copyable? Let me know if you'd like me to point it out via Vercel.

No, it's just for styling,`MDXCodeHighlighter` always has the copy button @PrintRH

**Comment by PrintRH** [comment]
@yqrashawn - Yes, that makes sense. But what I mean was if we reference the image below as an example, there is another container (light blue) which wraps the code. I wonder if we can have this removed (assuming now that the intention is not to separate code snippet that can be copied vs not copied).

example

**Comment by yqrashawn** [comment]
Thanks @PrintRH, it's fixed

**Review by PrintRH — APPROVED** [review]
LGTM!

Thanks for this PR @yqrashawn !

**Pull request merged**
