### PR TITLE
add 0x challenge to Level Up

### PR DESCRIPTION
**Pull request by jlin27**
## Content

As part of the 0x launch on Scroll, we want to encourage builders to build with 0x Swap API on Scroll with this 0x Challenge. It is a sequel to the [How to fetch live swap prices with 0x Swap API on Scroll](https://www.levelup.xyz/content/0x-on-scroll) Content.

The related code for the challenge is in this PR: https://github.com/LevelUpWeb3/0xSwapAPI-Challenge/pull/1

This PR also replaces all mentions of DAI with wstETH in the [How to fetch live swap prices with 0x Swap API on Scroll](https://www.levelup.xyz/content/0x-on-scroll) guide for consistency.
## Test

```
npm install
npm run build
npm run start
```

Review the guide at `Challenges > Get Started with 0x Swap API on Scroll`

### CODE REVIEW

**Review by emilyJLin95 — APPROVED** [review]
LGTM

**Comment by emilyJLin95** [comment]
Left some comments on vercel side, waiting for @PrintRH to see if we can get you permissions to add the 0x challenge repo to Level Up org

**Comment by jlin27** [comment]
Looks like I don't have permission to view the vercel deployment :( Can you drop your comments with screenshots here?

**Comment by PrintRH** [comment]
Heya @jlin27 , was there a button for you to request for Vercel preview? Else, I can reach out to you for your email and grant access.

**Comment by jlin27** [comment]
@PrintRH - Just requested access through the button 🙏

**Comment by jlin27** [comment]
@PrintRH - Also, what's your preferred method to create the repo for the challenge? Currently I have the code in my own repo since I don't have permission to create one in your github org: https://github.com/jlin27/0xSwapAPI-Challenge/tree/main/Challenge ? 

One option, if you could create a repo for me called `0xSwapAPI-Challenge` and I can make a PR to it?

**Review by emilyJLin95 — APPROVED** [review]
LGTM

**Pull request merged**
